---
title: "Gregor Mathes's CV"
author: Gregor Mathes
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1eF2wRaPknohXmXaRA1f9nfOarGwBhp--SqekUtclCww/edit#gid=917338460",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _https://gregor-mathes.netlify.app/#cv_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/Ischi94/CV/blob/master/cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Last updated on `r Sys.Date()`.



Main
================================================================================

Gregor Mathes {#title}
--------------------------------------------------------------------------------
<br>  

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
``` 

<br>
<br>
<br>

  

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```

\newpage





Selected Publications, Posters, and Talks {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')

CV %<>% print_section('presentations')
``` 

<br>
<br>


Software development {data-icon=cloud}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('software_aside')
``` 
:::

```{r}
CV %<>% print_section('software') 
```  


\newpage





Industry Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside

```{r}
CV %<>% print_text_block('industry_experience_aside')
```
:::

```{r}
CV %<>% print_section('industry_positions')
``` 

<br>
<br>


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('teaching_positions')
``` 

<br>
<br> 
 


Selected Awards and Honors {data-icon=star}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('awards_and_honors')
``` 


<br>
<br> 
 

Science outreach {data-icon=comment}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('outreach_aside')
``` 
:::

```{r}
CV %<>% print_section('outreach')
```


<br>
<br> 




<!-- Selected Data Science Writing {data-icon=edit} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('data_science_writing_aside') -->
<!-- ``` -->
<!-- ::: -->

<!-- ```{r} -->
<!-- CV %<>% print_section('data_science_writings') -->
<!-- ``` -->


<br>
<br>


Attended workshops {data-icon=chart-line}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('courses')
```



<br>
<br>



```{r}
CV %<>% print_links()
```

